language: generic

before_install:
    - if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew tap vapor/tap;
            brew update;
            brew install vapor;
        else
            eval "$(curl -sL https://apt.vapor.sh)";
            sudo apt-get install vapor;
            sudo chmod -R a+rx /usr/;
        fi

script:
    - swift build -Xcc -fbracket-depth=264
    
branches:
  only:
    - master
    - develop
    - /^\d+\.\d+.*/
os:
  - linux
  - osx
sudo: required
dist: trusty

osx_image: xcode8.3
