language: generic

before_install:
    - if [ $TRAVIS_OS_NAME != "osx" ]; then
            sudo apt-get update; sudo apt-get install -y libssl-dev zlib1g-dev sqlite3 libsqlite3-dev;
            eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
            sudo chmod -R a+rx /usr/;
        fi

script:
    - swift build --target mmd-swift
    
branches:
  only:
    - master
    - develop
    - /^\d+\.\d+.*/
os:
  - linux
  - osx
sudo: required
dist: trusty

osx_image: xcode11
